# Рекомендуемая конфигурация для Nginx / aaPanel URL Rewrite

location / {
    try_files $uri $uri/ /index.php?$query_string;
}

# Запрет доступа к скрытым и конфигурационным файлам
location ~ /\.(env|git|osp) {
    deny all;
    return 404;
}

# Запрет доступа к дампам и логам
location ~ \.(sql|log|ini)$ {
    deny all;
    return 404;
}
